<%@ Page Title="" Language="C#" MasterPageFile="~/JobMaster.Master" AutoEventWireup="true" CodeBehind="RecruiterGrid.aspx.cs" Inherits="JobPortal.Web.RecruiterGrid" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <div>
        <table>
            <tr>
                <td>
                    <asp:GridView ID="RecruiterView" runat="server" AutoGenerateColumns="False" DataKeyNames="AccountId" AutoGenerateDeleteButton="True"
                        AutoGenerateEditButton="True" OnRowUpdating="GridView_RowUpdating" OnRowCancelingEdit="GridView_RowCancelingEdit"
                        OnRowDeleting="GridView_RowDeleting" OnRowEditing="GridView_RowEditing" ShowFooter="true">
                        <Columns>
                            <asp:TemplateField HeaderText="Id" runat="server">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TxtId" runat="server" Text='<%# Bind("Id") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:LinkButton ID="BtInsert" Text="Insert" runat="server" OnClick="GridView_Inserting" />
                                </FooterTemplate>

                                <ItemTemplate>
                                    <asp:Label ID="LabelSalary" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Salary" runat="server">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TxtSalary" runat="server" Text='<%# Bind("Salary") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="LabelSalary" runat="server" Text='<%# Bind("Salary") %>'></asp:Label>
                                </ItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="txtSalary" runat="server" Text='<%# Bind("Salary") %>'></asp:TextBox>
                                </FooterTemplate>
                            </asp:TemplateField>
                           

                            <asp:TemplateField HeaderText="Location" runat="server">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TxtLocation" runat="server" Text='<%# Bind("Location") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="LabelLocation" runat="server" Text='<%# Bind("Location") %>'></asp:Label>
                                </ItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="txtLocation" runat="server" Text='<%# Bind("Location") %>'></asp:TextBox>
                                </FooterTemplate>
                            </asp:TemplateField>

                             <asp:TemplateField HeaderText="Position" runat="server">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TxtPosition" runat="server" Text='<%# Bind("Position") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="LabelPosition" runat="server" Text='<%# Bind("Position") %>'></asp:Label>
                                </ItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="txtPosition" runat="server" Text='<%# Bind("Position") %>'></asp:TextBox>
                                </FooterTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Graduation" runat="server">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TxtGraduation" runat="server" Text='<%# Bind("Graduation") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="LabelGraduation" runat="server" Text='<%# Bind("Graduation") %>'></asp:Label>
                                </ItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="txtGraduation" runat="server" Text='<%# Bind("Graduation") %>'></asp:TextBox>
                                </FooterTemplate>
                            </asp:TemplateField>

                            <asp:TemplateField HeaderText="WorkExpereince" runat="server">
                                <asp:EditItemTemplate>
                            <asp:TextBox ID="TxtWorkExperience" runat="server" Text='<%# Bind("WorkExperience") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="LabelWorkExperience" runat="server" Text='<%# Bind("WorkExperience") %>'></asp:Label>
                                </ItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="txtWorkExperience" runat="server" Text='<%# Bind("WorkExperience") %>'></asp:TextBox>
                                </FooterTemplate>
                            </asp:TemplateField>

                              <asp:TemplateField HeaderText="JobType" runat="server">
                                <asp:EditItemTemplate>
                            <asp:TextBox ID="TxtType" runat="server" Text='<%# Bind("Type") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="LabelType" runat="server" Text='<%# Bind("Type") %>'></asp:Label>
                                </ItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="txtType" runat="server" Text='<%# Bind("Type") %>'></asp:TextBox>
                                </FooterTemplate>
                            </asp:TemplateField>

    </Columns>
</asp:Content>
